### ISSUE TITLE
Cannot find module multimatch 

### ISSUE THREAD

**Issue by antoniogamiz** [SamKirkland/ftp-deploy#10]
When I try to run the example I get the following error:

~~~
➜  example node deploy.js
internal/modules/cjs/loader.js:613
    throw err;
    ^

Error: Cannot find module 'multiMatch'
Require stack:
- /home/antonio/example/node_modules/@samkirkland/ftp-deploy/dist/module.js
- /home/antonio/example/deploy.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
    at Function.Module._load (internal/modules/cjs/loader.js:526:27)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/antonio/example/node_modules/@samkirkland/ftp-deploy/dist/module.js:39:38)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
~~~

**Comment by SamKirkland** [comment]
See issue #9 

I'll be fixing this soon. Please update Match to a lower case m to fix the issue on your local.
multiMatch --> multimatch
