### ISSUE TITLE
Cannot find module 'multiMatch'

### ISSUE THREAD

**Issue by lotiviot** [SamKirkland/ftp-deploy#9]
**STEPS TO REPRODUCE**

1. create new project `npm init -y`
2. install library `npm i @samkirkland/ftp-deploy`
3. write the following script into the `package.json` -> `"test": "ftp-deploy --server someftps.server.com --username *** --password ***"
`

**Expected Result**
Since this deployment would be to an ftps server, I would expect an error on the server type as I am not including `--protocol ftps`.

**Actual Result**
The following output is what occurs. 
```
Error: Cannot find module 'multiMatch'
Require stack:
- /home/runner/work/trx-now-webapp/trx-now-webapp/node_modules/@samkirkland/ftp-deploy/dist/module.js
- /home/runner/work/trx-now-webapp/trx-now-webapp/node_modules/@samkirkland/ftp-deploy/dist/cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/runner/work/trx-now-webapp/trx-now-webapp/node_modules/@samkirkland/ftp-deploy/dist/module.js:39:38)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/trx-now-webapp/trx-now-webapp/node_modules/@samkirkland/ftp-deploy/dist/module.js',
    '/home/runner/work/trx-now-webapp/trx-now-webapp/node_modules/@samkirkland/ftp-deploy/dist/cli.js'
  ]
}
```

**Possible Solution**
I can't think of anything off the top of my head, but what I do know is that somehow to call for multiMatch doesn't occur as it should on my local machine after installing directly from npm. 

Please Advise.

**Comment by SamKirkland** [comment]
I'll be fixing this soon. Please update `Match` to a lower case `m` to fix the issue on your local.
`multiMatch` --> `multimatch`

**Comment by lotiviot** [comment]
Thanks for the shorthand fix!
